# Generated by Django 3.2.3 on 2021-05-31 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gazon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_cat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gazon.servicecat'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Название сервиса'),
        ),
    ]
