# Generated by Django 3.2.3 on 2021-06-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazon', '0002_auto_20210531_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='Название фотографии')),
                ('service', models.CharField(blank=True, max_length=30, verbose_name='Название услуги')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание фотографии')),
            ],
            options={
                'verbose_name': 'Фото из галереи',
                'verbose_name_plural': 'Фото из галереи',
            },
        ),
    ]
