# Generated by Django 3.2.3 on 2021-06-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazon', '0003_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Фото для галереи', 'verbose_name_plural': 'Фото для галереи'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_1',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 1 на Главной'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_2',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото 2 на Главной'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_big',
            field=models.FileField(blank=True, upload_to='', verbose_name='Увеличенное фото'),
        ),
    ]
