# Generated by Django 3.2.3 on 2021-06-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gazon', '0004_auto_20210602_0827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='FeedbackPhone',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceCat',
        ),
    ]
