# Generated by Django 3.2.3 on 2021-06-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazon', '0005_auto_20210602_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Большое фото в шапке')),
                ('logo', models.FileField(blank=True, upload_to='', verbose_name='Логотип')),
                ('welcome', models.CharField(blank=True, max_length=30, verbose_name='Приветствие')),
                ('text', models.CharField(blank=True, max_length=120, verbose_name='Крупный текст на фото')),
            ],
            options={
                'verbose_name': 'Шапка',
                'verbose_name_plural': 'Шапка',
            },
        ),
    ]
