# Generated by Django 3.2.3 on 2021-06-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazon', '0006_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.FileField(blank=True, upload_to='', verbose_name='Вступительная фраза')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=800, verbose_name='Текст о компании')),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'О компании',
            },
        ),
    ]
