# Generated by Django 3.2.3 on 2021-06-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazon', '0008_auto_20210602_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(blank=True, max_length=50, verbose_name='Вступительная фраза')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок')),
                ('service', models.CharField(blank=True, max_length=50, verbose_name='Название услуги')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
