# Generated by Django 3.2.3 on 2021-06-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazon', '0011_auto_20210602_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название раздела'),
        ),
    ]
