# Generated by Django 3.2.3 on 2021-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazon', '0012_alter_service_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код флатикона'),
        ),
    ]
