# Generated by Django 3.2.3 on 2021-06-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazon', '0013_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='header',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок раздела'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='intro',
            field=models.CharField(blank=True, max_length=30, verbose_name='Вступительная фраза'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_1',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото х1'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_2',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото х2'),
        ),
    ]
