# Generated by Django 3.2.3 on 2021-06-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazon', '0014_auto_20210602_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя, фамилия')),
                ('testimonial', models.CharField(blank=True, max_length=800, verbose_name='Отзыв')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото человека')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_big',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фото по клику'),
        ),
    ]
