# Generated by Django 3.2.3 on 2021-06-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazon', '0015_auto_20210603_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=models.CharField(blank=True, max_length=300, verbose_name='Отзыв'),
        ),
    ]
